### ISSUE TITLE
Uppercase for plugins

### ISSUE THREAD

**Issue by alain01** [mambax7/rssfit#4]
Hi,
I think i's better to use lower case for the module name in the plugin directory

Same for the files in the class directory 
and Common directory
and theses 2 directory: Common and Plugins

**Comment by mambax7** [comment]
That's a standard PHP convention that we're using ([PSR-1](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md),  [PSR-2](https://www.php-fig.org/psr/psr-2/))
